### ISSUE TITLE
Incorrect weather

### ISSUE THREAD

**Issue by ishtiaq156** [nadeemansaris524968/node-weather-app#1]
Steps to reproduce:

- Search for "Durham" city.

Durham is a city in NC, United States.

<img width="937" alt="Screen Shot 2020-10-29 at 4 57 32 PM" src="https://user-images.githubusercontent.com/25985759/97632062-5a2ea900-1a08-11eb-991f-d586f83a343c.png">

**Comment by nadeemansaris524968** [comment]
Yes this happens unfortunately because the Geocoding service actually returns a broad set of coordinates which is off by at least 10-15 miles, hence the difference in name.
